name: Contracts
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn
      - working-directory: packages/contracts
        run: |
          yarn run build
